version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: nnha
      POSTGRES_PASSWORD: nnha
      POSTGRES_DB: embedded
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nestjs_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nnha
      DATABASE_PASSWORD: nnha
      DATABASE_NAME: embedded
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
